### PR TITLE
updating file to be compatible with PyStan 3

### PR DESCRIPTION
**Pull request by sjdritz**
Let me know if you think these edits are correct!

### CODE REVIEW

**Comment by jg-you** [comment]
Just did a bit of reading on pystan version 3 and the changes are major and definitely not backward compatible.
Model loading/caching seems to be handled automatically.
So that simplifies compilation a bit but also changes the abstraction (no need to build and pickle).

On the other hand: seeding and data are fixed at compilation. That requires a different build everytime.
And finally, the axes of the sampling objects have been shuffled around, e.g., the Q matrix samples, which were previously indexed as [sample,plant,polinator] are now indexed as [plant.pollinator,sample_id] so all the average functions and so on are broken. 

Quite a bit of work to add to the edits I think .. :/


This is too different to warrant an override of the codebase, I will still support pystan 2.19

I did some partial work to accommodate pystan3 on this branch: https://github.com/jg-you/plant-pollinator-inference/tree/UPDATE 

with a second notebook and python file just for pystan3. Still have to figure out indexing for the posterior predictive part.

**Comment by sjdritz** [comment]
Hi

I actually made some additional edits which handle the reordering of the sampled data, however I did get stuck at the sampling loop which just generates the same samples every time like you mentioned.

I can submit a pull request for what I’ve worked on so far and I’m happy to keep working on it,

Sabine
________________________________

**Comment by sjdritz** [comment]
I just now saw that you also started a notebook and python file for pystan3, but I wanted to let you know that I just finished updating the notebook and python file I was working on. The notebook runs and the output is the same (I was able to fix the indexing issue) if you want to use any of my code in your pystan3 files!

**Comment by jg-you** [comment]
Great work, and the changes look good now!

I can merge this pull request to make your contributions available to others who follow the URL, with a few more small tweaks I think:

-  For the sake of backward compatibility, it would be best to rename all the files with a pystan3 suffix (plant_pol_inference_pystan3.py,  model_pystan3.stan, etc.) so that they do not overwrite the pystan2 versions.
- A few code things:  L51 of plant_pol_inference: `random.randrange(0, 100)` is not needed I think, pystan3 will already bake-in a fixed seed pixed at random.
- `plant_pol_inference_updated.ipynb` can be dropped from the final version
- Add your name to the code authors!

**Comment by sjdritz** [comment]
Ok great! I renamed the files, dropped the plant_pol_inference_updated.ipynb file, added my name to the code authors, and updated the text in the python example. I left the random.randrange(0,100) because without it the resampling in the python example was generating the same results each time, I'm not sure why the random seed was not automatically updating.

**Comment by jg-you** [comment]
This is awesome! One last little change would be to also have a pystan3 version for the model itself since the array[ , ] notation is not backward compatible.

**Comment by sjdritz** [comment]
Right that makes sense, I just renamed the .stan file and changed the model path in the notebook and python file. Do we have to worry about warnings generated that none of the parameters have priors? 

I was reading about the warnings here:
https://mc-stan.org/docs/2_27/reference-manual/parameters-with-zero-or-multiple-priors.html

**Comment by jg-you** [comment]
Ah that makes sense! But yeah, pystan2 ships with an older build of stan itself, and they don't support the array notation. Thanks!

I think the code is ready to merge. 
Our model use uniform priors which is effectively what happens when non are specified. So they can be added to make the warnings go away, but that won't change _behavior_.

**Comment by sjdritz** [comment]
Ok sweet! I just made a couple edits in the notebook text, but I think its ready to merge too.

**Comment by jg-you** [comment]
Thank you for your fantastic work on this Sabine!

**Comment by sjdritz** [comment]
Of course! I’m excited to try this method with my data. One last note, I see that model.stan was deleted during the merge because I modified that file directly in my repository to update it to model_pystan3.stan, do you want to restore the original file so that both versions are in the repository?

From: Jean-Gabriel Young ***@***.***>
Date: Thursday, April 7, 2022 at 11:54 AM
To: jg-you/plant-pollinator-inference ***@***.***>
Cc: Sabine Jordan Dritz ***@***.***>, Author ***@***.***>
Subject: Re: [jg-you/plant-pollinator-inference] updating file to be compatible with PyStan 3 (PR #1)

Merged #1<https://github.com/jg-you/plant-pollinator-inference/pull/1> into master.

**Comment by jg-you** [comment]
Ah that's ok I can fix it!

**Pull request merged**
